# Generated by Django 3.2.8 on 2021-10-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('video_file', models.FileField(null=True, upload_to='videos/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
