# Generated by Django 3.2.8 on 2021-10-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_remove_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='yolo_file',
            field=models.FileField(blank=True, upload_to='yolovideos'),
        ),
    ]
