# Generated by Django 3.2.8 on 2021-10-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0003_video_yolo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='yolo_file',
        ),
    ]
