# Generated by Django 3.2.8 on 2021-10-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0005_video_yolo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='yolo_file',
            field=models.FileField(null=True, upload_to='yolovideos/'),
        ),
    ]
